version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=simple_bank  
    healthcheck:
    # 这里必须指定user和db，否则会报错
      test: [ "CMD-SHELL", "pg_isready -U root -d simple_bank" ]
      timeout: 45s
      interval: 10s
      retries: 10
  api: 
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://root:123456@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy